theme: jekyll-theme-midnight
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - eru-setup.md
  - eru-outline.md
  - eru-github-pages-extra.md
  - eru-day1-2.md
  - eru-day3-4.md

title: Electronics for the Rest of Us!
description: Jay Brodeur | INSPIRE 1A03 | Spring, 2020
